# Generated by Django 4.1.7 on 2023-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='FOO', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='FOO', max_length=100),
        ),
    ]
